/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as vaultSol from "./Vault.sol";
export type { vaultSol };
import type * as providers from "./providers";
export type { providers };
export type { User } from "./User";
