/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as chainlink from "./@chainlink";
export type { chainlink };
import type * as contracts from "./contracts";
export type { contracts };
export * as factories from "./factories";
export type { AutomationBase } from "./@chainlink/contracts/src/v0.8/automation/AutomationBase";
export { AutomationBase__factory } from "./factories/@chainlink/contracts/src/v0.8/automation/AutomationBase__factory";
export type { AutomationCompatible } from "./@chainlink/contracts/src/v0.8/automation/AutomationCompatible";
export { AutomationCompatible__factory } from "./factories/@chainlink/contracts/src/v0.8/automation/AutomationCompatible__factory";
export type { AutomationCompatibleInterface } from "./@chainlink/contracts/src/v0.8/automation/interfaces/AutomationCompatibleInterface";
export { AutomationCompatibleInterface__factory } from "./factories/@chainlink/contracts/src/v0.8/automation/interfaces/AutomationCompatibleInterface__factory";
export type { LifeSignal } from "./contracts/providers/LifeSignal";
export { LifeSignal__factory } from "./factories/contracts/providers/LifeSignal__factory";
export type { User } from "./contracts/User";
export { User__factory } from "./factories/contracts/User__factory";
export type { Vault } from "./contracts/Vault.sol/Vault";
export { Vault__factory } from "./factories/contracts/Vault.sol/Vault__factory";
export type { VaultManager } from "./contracts/Vault.sol/VaultManager";
export { VaultManager__factory } from "./factories/contracts/Vault.sol/VaultManager__factory";
