sequenceDiagram
    participant User
    participant OASIS Sapphire
    participant Heir

    Note over User: User is still alive
    Note over Heir: Contacts can signal the user death. A contact can be associated to a vault (heir)
    User->>OASIS Sapphire: call function to modify heirs (modify, add, remove)
    User->>OASIS Sapphire: call function to modify contacts (modify, add, remove)

    Note over User: User is declared dead

    User->>OASIS Sapphire : call function to give access of the content of the vault to the heirs
    OASIS Sapphire ->>Heir: heirs can know view and decrypt files stored in the vault

