sequenceDiagram
    participant User
    participant OASIS Sapphire

    User->>User: create KEY
    activate User
    User-->>User: KEY created
    deactivate User

    User->>User: create vault : a Smart Contract
    activate User
    User-->>User: vault created
    deactivate User

    User->>OASIS Sapphire: publish on OASIS Sapphire